// <auto-generated />
namespace VirtualPiano.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_234));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291141581_234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
